---
dist: xenial
language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'
install:
  - pip install tox
  - make venv
script:
  # Travis only supports one python version per environment (pyenv).Tox doesn't support running all permutations of a
  # factor. They found each other, though the magic of grep and sed.
  - export PY_VERSION=$(echo "${TRAVIS_PYTHON_VERSION}" | sed 's/\.//')
  - export TOXENV=$(tox --listenvs | grep "py${PY_VERSION}-" | tr '\n' ',')
  - tox
  # We probably don't need to run this for every environment. Probably shouldn't. I'll fix it if it becomes a problem
  - tox -e project_tests
cache:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit
