---
dist: xenial
language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'
install:
  - pip install tox coveralls
  - make venv
script:
  # Travis only supports one python version per environment (pyenv).Tox doesn't support running all permutations of a
  # factor. They found each other, though the magic of grep and sed.
  - export PY_VERSION=$(echo "${TRAVIS_PYTHON_VERSION}" | sed 's/\.//')
  - export TOXENV=$(tox --listenvs | grep "py${PY_VERSION}-" | tr '\n' ',')
  - tox
  - if test "$TRAVIS_PYTHON_VERSION" == '3.7'; then tox -e project_tests; fi
after_success:
  - coveralls
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
